add .Index to every cell
TheDataShed/xlsxreader pull request #24
Opened 2020-11-10 15:58 UTC by alicebob

First of all thanks for a simple XLSX reader. I added a link to my similarly simple XLSX writer: https://github.com/alicebob/streamxlsx

This PR adds the index of every cell, which is calculated from the Column (`AA` &c.). This makes it easier for me to process the rows. If you prefer it as a standalone function I can obviously change it as well, but it seems to me a common thing to need.

The `asCol` function is copied from the mentioned repo, which is MIT licensed. But it's only used in a test, so if that's a problem you can easily remove it. The `asIndex` I wrote myself, so no license problems there.

2020-11-10 16:20 UTC, dglsparsons requested changes

2020-11-10 16:20 UTC, dglsparsons commented on rows_test.go
> +		require.Equal(t, s, asCol(n)) // test the test
This isn't really testing the test - it's testing the `asCol` method. Which seems a bit irrelevant. 

I think we could remove this line and remove the `asCol` function.

2020-11-10 16:20 UTC, dglsparsons commented on rows.go
> +	Index  int
I'm not a big fan of the name here - although I can definitely see the benefit in holding the Index of a column. 

Could I suggest we turn this into a `ColumnIndex` field instead. 

For consistency, we should probably have a `RowIndex` too (which is the same as `Row - 1`).

2020-11-10 16:20 UTC, dglsparsons commented on rows_test.go
> +	test("A", 0)
This would be preferred as a Table Driven Test (https://github.com/golang/go/wiki/TableDrivenTests), rather than one test with lots of lines.

2020-11-10 16:21 UTC, dglsparsons commented
Hi @alicebob. Thanks for the contribution - I'm glad the xlsxreader has helped you out. 

I've added a few comments to your Pull Request - mostly around naming and tidying up. 

@AndyThurgood Could you take a nosey at this too, as a repository owner?

2020-11-10 19:13 UTC, alicebob commented
Hi @dglsparsons , thanks for the quick reply!

I updated the code, except the "RowIndex" change, which sounds nicer if you add that.

2020-11-17 07:33 UTC, dglsparsons commented
Bumping @AndyThurgood for this. 

I'm not sure this makes sense with a ColumnIndex but no RowIndex though :thinking:

2020-11-23 09:44 UTC, alicebob commented
@dglsparsons : made the change you suggested. We could also do it differently: rename the `asIndex()` function to `ColumnIndex()`, and not add anything to `Cell{}`. Then it's a plain old function, which I find even nicer, personally.

2020-11-23 09:56 UTC, dglsparsons commented
Personally, I think I prefer it on the `Cell{}` - when using the library I think 
```go
cell, err := // read row
i := cell.ColumnIndex()
```
reads nicer than 
```go
cell, err := // read row
I := xlsxreader.ColumnIndex(cell.Column)
```

2020-11-23 09:57 UTC, dglsparsons commented
I'm happy with the change personally, but I don't work at TheDataShed anymore, so don't have the power to merge this :(

2020-11-23 10:00 UTC, alicebob commented
> but I don't work at TheDataShed anymore

Ah! That explains some things. Thanks for your feedback, btw.

2020-11-23 10:59 UTC, dglsparsons commented
Happy to help. Thanks for the contributions <3

2020-12-01 16:51 UTC, dglsparsons approved these changes

2020-12-01 16:58 UTC, AndyThurgood approved these changes

2020-12-01 17:19 UTC, merged